base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_page, name="home"),
    path("login/", views.login_page, name="login"),
    path("register/", views.register_page, name="register"),
    path("logout/", views.logout_page, name="logout"),
    path("user/<int:pk>/", views.user_page, name="profile"),
    path("event/<int:pk>/", views.event_page, name="event"),
    path(
        "registration-confirmation/<int:pk>/",
        views.registration_confirmation,
        name="registration-confirmation",
    ),
    path("account/", views.account_page, name="account"),
    path(
        "project-submission/<int:pk>/",
        views.project_submission,
        name="project-submission",
    ),
    path(
        "update-submission/<int:pk>/", views.update_submission, name="update-submission"
    ),
]

codebattle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True)
    bio = models.TextField(null=True, blank=True)
    hackthon_participant = models.BooleanField(default=True, null=True)

    avatar = models.ImageField(default='/images/avatar.png')
    # avatar =
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]


class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, blank=True)
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    registration_deadline = models.DateTimeField(null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Submission(models.Model):
    participant = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True)
    details = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.event) + " --- " + str(self.participant)

base/forms.py
from django.forms import ModelForm
from .models import Submission, User
from django.contrib.auth.forms import UserCreationForm


class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        fields = ["details"]


class CustomUserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "name", "password1", "password2"]

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse


from .models import User, Event, Submission
from .forms import SubmissionForm, CustomUserCreateForm

# Create your views here.


def login_page(request):
    page = "login"
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")

    return render(request, "login_register.html", {"page": page})


def register_page(request):
    page = "register"
    form = CustomUserCreateForm()

    if request.method == "POST":
        form = CustomUserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            login(request, user)
            return redirect("home")
    return render(request, "login_register.html", {"page": page, "form": form})


def logout_page(request):
    logout(request)
    return redirect("login")


def home_page(request):
    users = User.objects.filter(hackthon_participant=True)
    events = Event.objects.all()
    context = {"users": users, "events": events}
    return render(request, "home.html", context)


def user_page(request, pk):
    user = User.objects.get(id=pk)
    return render(request, "profile.html", {"user": user})


@login_required(login_url="/login")
def account_page(request):
    return render(request, "account.html", {"user": request.user})


def event_page(request, pk):
    event = Event.objects.get(id=pk)

    registered = False
    submitted = False

    if request.user.is_authenticated:
        registered = request.user.event_set.filter(id=event.id).exists()
        submitted = Submission.objects.filter(
            participant=request.user, event=event
        ).exists()

    return render(
        request,
        "event.html",
        {"event": event, "registered": registered, "submitted": submitted},
    )


@login_required(login_url="/login")
def registration_confirmation(request, pk):
    event = Event.objects.get(id=pk)
    try:
        event.participants.add(request.user)
        return redirect("event", pk=event.id)
    except:
        return render(request, "event_confirmation.html", {"event": event})


@login_required(login_url="/login")
def project_submission(request, pk):
    event = Event.objects.get(id=pk)
    form = SubmissionForm()
    if request.method == "POST":
        form = SubmissionForm(request.POST)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.participant = request.user
            submission.event = event
            submission.save()
            return redirect("account")
    return render(request, "submit_form.html", {"event": event, "form": form})


@login_required(login_url="/login")
def update_submission(request, pk):
    submission = Submission.objects.get(id=pk)

    if request.user != submission.participant:
        return HttpResponse('You cant be here!!!!')
        
    event = submission.event
    form = SubmissionForm(instance=submission)
    if request.method == "POST":
        form = SubmissionForm(request.POST, instance=submission)
        if form.is_valid():
            form.save()
            return redirect("account")
    return render(request, "submit_form.html", {"form": form, "event": event})

templates/account.html
{% extends 'base.html' %}

{% block content %}
    <h1>My account</h1>

    <div>
        <h3>My Events</h3>
        {% for event in user.event_set.all %}
           <a href="{% url 'event' event.id %}">{{event.name}}</a>
        {% endfor %}
    </div>

    <div>
        <h3>My Submissions</h3>
        {% for sub in user.submission_set.all %}
           <a href="{% url 'update-submission' sub.id %}">{{sub.event.name}}</a>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script> -->
</head>
<body>
    <main>
        {% include 'navbar.html' %}
        <div class="container--main">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    
</body>
</html>

templates/event.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{event.name}}</h1>
    {% if registered %}
        <p>You have already registed for this event</p>
    {% else %}
        <a href="{% url 'registration-confirmation' event.id %}" id='confirm-event'>Register For Event</a>
    {% endif %}
    
    {% if submitted %}
        <p>You have already submitted your project</p>
    {% else %}
        <a href="{% url 'project-submission' event.id %}">Submit Project</a>
    {% endif %}

    <p>{{event.description}}</p>

    <div>
        <h3>Event Participants</h3>

        <div>
            {% for user in event.participants.all %}
                <div>
                    <strong>{{user.name}}</strong>
                </div>
            {% endfor %}
        </div>
    </div>

<script>
    $(document).on('click', '#confirm-event', function(){
        return confirm('Confirm?');
    })
</script>
{% endblock %}

templates/event_confirmation.html
{% extends 'base.html' %}

{% block content %}
    Try again!
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}


    <section class="container--events">
        <h3>Events</h3>

        <div class="events--lists">
            {% for event in events %}
                <a href="{% url 'event' event.pk %}">
                    <div class="wrapper--event">
                        <strong>{{event.name}}</strong>
                        <p>{{event.participants.count}} registered</p>
                        <p>Registration deadline: {{event.registration_deadline}}</p>
                    </div> 
                </a>
            {%endfor%}
        </div>

    </section>

    <section>
        <h3>Users</h3>
        
        
        <div class="user--lists">
            {% for user in users %}
            
            <a href="{% url 'profile' user.id %}">    
                <div class="wrapper--user">
                    <h4>{{user.name}}</h4>
                </div>
            </a>
            
            {%endfor%}
        </div>
        
    </section>
{% endblock %}

templates/login_register.html
{% extends 'base.html' %}

{% block content %}

    
    {% if page == 'register' %}
        <h1>Register</h1>
        <div>
            <form action="{% url 'register' %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit">
            </form>
        </div>

        <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
    {% else %}
        <h1>Login user</h1>

        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}

            <!-- <div>
                <label>User: </label>
                <input type="text" name="username"/>
            </div> -->
            <div>
                <label>Email: </label>
                <input type="email" name="email"/>
            </div>
            <div>
                <label>Password: </label>
                <input type="password" name="password"/>
            </div>
            <div>
                <input type="submit">
            </div>
            <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
        </form>
    {% endif %}

{% endblock %}

templates/navbar.html
<nav>
    <div>
        
        <a href="{% url 'home' %}">Home</a>
        
        {% if request.user.is_authenticated %}
            <a href="{% url 'account' %}">My Account</a>
        {% endif%}
    </div>

    <div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</nav>

templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{user.name}}</h1>
    
{% endblock %}

templates/submit_form.html
{% extends 'base.html' %}

{% block content %}
    <h4>Submit project for {{event.name}}</h4>

    <div>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit">
        </form>
    </div>
{% endblock %}